-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

-- NGame

NDefines.NGame.DAYS_BEHIND_PAUSE = 60	
NDefines.NGame.DAYS_BEHIND_LOWER_SPEED = 30

--NDiplomacy

NDefines.NDiplomacy.UNCONDITIONAL_SURRENDER_MONTHS = 1
NDefines.NDiplomacy.ABDICATE_LEGITIMACY_HIT = -10
NDefines.NDiplomacy.ABDICATE_PRESTIGE_HIT = -30
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.INTEGRATE_UNION_MIN_YEARS = 40
NDefines.NDiplomacy.STABHIT_FOR_BREAKING_ALLIANCE_IN_WAR = 0
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_LOSE = 0
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_GAIN = 0
NDefines.NDiplomacy.MAX_ASKED_TRADE_POWER = 100
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = 0

NDefines.NDiplomacy.DEFENDER_OF_FAITH_TRUST_LOSS = -1
NDefines.NDiplomacy.DEFENDER_OF_FAITH_PENALTY_DAYS = 1
NDefines.NDiplomacy.DEMAND_UNLAWFUL_TERRITORY_BASE_DESIRE = -200
NDefines.NDiplomacy.DEMAND_UNLAWFUL_TERRITORY_DEPENDENCY_DESIRE = 0
NDefines.NDiplomacy.DEMAND_UNLAWFUL_TERRITORY_ALLIANCE_DESIRE = 0
NDefines.NDiplomacy.DEMAND_UNLAWFUL_TERRITORY_TARGET_AT_WAR_DESIRE = 0
NDefines.NDiplomacy.DEMAND_UNLAWFUL_TERRITORY_RIVALRY_DESIRE = 0
NDefines.NDiplomacy.DEMAND_UNLAWFUL_TERRITORY_DESIRE_OPINION_MODIFIER = 0
NDefines.NDiplomacy.DEMAND_UNLAWFUL_TERRITORY_DESIRE_TRUST_MODIFIER = 0
NDefines.NDiplomacy.DEMAND_UNLAWFUL_TERRITORY_DESIRE_AE_MODIFIER = 0
NDefines.NDiplomacy.MIN_PAPAL_INFLUENCE_TO_PREVENT_EXCOMMUNICATION = 25
NDefines.NDiplomacy.AUTONOMY_WARSCORE_COST_MODIFIER = 1


NDefines.NDiplomacy.CONDOTTIERI_MIN_DURATION = 1

NDefines.NDiplomacy.REVANCHISM_MONTHLY_DECAY = 0.5

NDefines.NDiplomacy.AUTODIPLO_TARGET_COALITION_IMPROVECAP = 51

-- NCountry

NDefines.NCountry.BASE_POWER_INCREASE = 4
NDefines.NCountry.CLEAR_PROVINCE_VARIABLES_ON_CLEAR_OWNER = 0
NDefines.NCountry.CLEAR_PROVINCE_FLAGS_ON_CLEAR_OWNER = 0	 
NDefines.NCountry.CLEAR_PROVINCE_SAVED_NAMES_ON_CLEAR_OWNER = 0

NDefines.NCountry.MIN_DEV_FOR_FREE_CITY = 1
NDefines.NCountry.MAX_PROVINCES_FOR_FREE_CITY = 10
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.ESTATE_CROWNLAND_FROM_DEV = 0.4
NDefines.NCountry.NAT_FOCUS_YEARS = 0
NDefines.NCountry.PS_ADD_ACCEPTED_CULTURE = 50
NDefines.NCountry.NUM_POSSIBLE_RIVALS = 4
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.2
NDefines.NCountry.MINIMUM_POLICY_TIME = 1
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.PS_STRENGTHEN_GOVERNMENT = 80
NDefines.NCountry.PS_REDUCE_INFLATION = 60
NDefines.NCountry.PS_PROMOTE_MERCANTILISM = 75
NDefines.NCountry.PS_ADVANCE_TECH = 500
NDefines.NCountry.PS_BUY_IDEA = 300
NDefines.NCountry.STRENGTHEN_GOVERNMENT_REPUBLICAN_TRADITION = 5
NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 4
NDefines.NCountry.NAVAL_FORCELIMIT_EXTRA_COST_FACTOR = 4

-- NEconomy

NDefines.NEconomy.AUTONOMY_AT_DIPLO_ANNEX = 40

-- NMilitary

NDefines.NMilitary.WARGOAL_MAX_BONUS = 50

-- GUI
NDefines.NGui.DELAY_ACCEPT_EVENT = 0.6		
NDefines.NGui.DELAY_ACCEPT_CALL_TO_ARMS = 0.6